site_name: Twitch Bot
site_description: A simple Twitch channel bot created on my live streamings for helping and interacting with my viewers/chat.
site_url: https://amandamartinsdev.github.io/twitch-bot/

repo_url: https://github.com/amandamartinsdev/twitch-bot
repo_name: amandamartinsdev/twitch-bot
edit_uri: tree/main/docs

copyright: This project is under GPL-3.0 license

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amandamartinsdev
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/amandamartinsdev
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/amandamartinsdev
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@mandys_
    - icon: fontawesome/brands/mastodon
      link: https://bolha.us/@amandamartinsdev
    - icon: fontawesome/brands/dev
      link: https://dev.to/amandamartinsdev
    - icon: fontawesome/brands/medium
      link: https://medium.com/@mandys_
    - icon: fontawesome/brands/itch-io
      link: https://amandamartins.itch.io/

plugins:
  - search
  - termynal
  - mkdocstrings:
      handlers:
        python:
          paths: [twitch_bot]
